# probably need to create c:\database before composing the app

version: '2.1'

services:

  nerd-dinner-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    networks:
      - nerd-dinner

  nerd-dinner-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - connection-strings.env
      # - secrets.env
    depends_on:
      - nerd-dinner-db
    networks:
      - nerd-dinner

networks:
  nerd-dinner:
    external:
      name: nat

